### ISSUE TITLE
Example `movie_reviews` not working

### ISSUE THREAD

**Issue by geblanco** [autogoal/autogoal#24]
Hello,

Following the `sklearn integration` example from the user guide I encountered some errors.
At first,

```bash
python docs/examples/sklearn_simple_grammar.py
<Pipeline>      := Pipeline (vectorizer=<Vectorizer>, decomposer=<Decomposer>, classifier=<Classifier>)
<Vectorizer>    := <Count> | <TfIdf>
<Count>         := Count (ngram=<Count_ngram>)
<Count_ngram>   := discrete (min=1, max=3)
<TfIdf>         := TfIdf (ngram=<TfIdf_ngram>, use_idf=<TfIdf_use_idf>)
<TfIdf_ngram>   := discrete (min=1, max=3)
<TfIdf_use_idf> := boolean ()
<Decomposer>    := <NoDec> | <SVD>
<NoDec>         := NoDec ()
<SVD>           := SVD (n=<SVD_n>)
<SVD_n>         := discrete (min=50, max=200)
<Classifier>    := <LR> | <SVM> | <DT>
<LR>            := LR (penalty=<LR_penalty>, reg=<LR_reg>)
<LR_penalty>    := categorical (options=['l1', 'l2'])
<LR_reg>        := continuous (min=0.1, max=10)
<SVM>           := SVM (kernel=<SVM_kernel>, reg=<SVM_reg>)
<SVM_kernel>    := categorical (options=['rbf', 'linear', 'poly'])
<SVM_reg>       := continuous (min=0.1, max=10)
<DT>            := DT (criterion=<DT_criterion>)
<DT_criterion>  := categorical (options=['gini', 'entropy'])
Pipeline(classifier=LR(penalty='l2', reg=3.5043071948123306),
         decomposer=NoDec(), vectorizer=TfIdf(ngram=1, use_idf=True))
Pipeline(classifier=SVM(kernel='poly', reg=9.486662105103457),
         decomposer=NoDec(), vectorizer=Count(ngram=3))
Pipeline(classifier=LR(penalty='l2', reg=3.7888734971195985),
         decomposer=SVD(n=117), vectorizer=Count(ngram=2))
Pipeline(classifier=DT(criterion='gini'), decomposer=SVD(n=131),
         vectorizer=Count(ngram=2))
Pipeline(classifier=LR(penalty='l1', reg=1.2230686432095683),
         decomposer=NoDec(), vectorizer=TfIdf(ngram=3, use_idf=False))
Pipeline(classifier=DT(criterion='gini'), decomposer=SVD(n=111),
         vectorizer=Count(ngram=3))
Pipeline(classifier=SVM(kernel='rbf', reg=6.572569333421884),
         decomposer=SVD(n=89), vectorizer=Count(ngram=1))
Pipeline(classifier=DT(criterion='entropy'), decomposer=NoDec(),
         vectorizer=Count(ngram=1))
Pipeline(classifier=LR(penalty='l1', reg=7.546789410143803),
         decomposer=SVD(n=140), vectorizer=Count(ngram=1))
Pipeline(classifier=LR(penalty='l1', reg=4.0054809098376065),
         decomposer=SVD(n=113), vectorizer=Count(ngram=2))
Traceback (most recent call last):
  File "docs/examples/sklearn_simple_grammar.py", line 298, in <module>
    logger = ProgressLogger(log_solutions=True)
TypeError: ProgressLogger() takes no arguments
```

Then, removing the parameter to the ProgressLogger, I get the following error:
```bash
python docs/examples/sklearn_simple_grammar.py
<Pipeline>      := Pipeline (vectorizer=<Vectorizer>, decomposer=<Decomposer>, classifier=<Classifier>)
<Vectorizer>    := <Count> | <TfIdf>
<Count>         := Count (ngram=<Count_ngram>)
<Count_ngram>   := discrete (min=1, max=3)
<TfIdf>         := TfIdf (ngram=<TfIdf_ngram>, use_idf=<TfIdf_use_idf>)
<TfIdf_ngram>   := discrete (min=1, max=3)
<TfIdf_use_idf> := boolean ()
<Decomposer>    := <NoDec> | <SVD>
<NoDec>         := NoDec ()
<SVD>           := SVD (n=<SVD_n>)
<SVD_n>         := discrete (min=50, max=200)
<Classifier>    := <LR> | <SVM> | <DT>
<LR>            := LR (penalty=<LR_penalty>, reg=<LR_reg>)
<LR_penalty>    := categorical (options=['l1', 'l2'])
<LR_reg>        := continuous (min=0.1, max=10)
<SVM>           := SVM (kernel=<SVM_kernel>, reg=<SVM_reg>)
<SVM_kernel>    := categorical (options=['rbf', 'linear', 'poly'])
<SVM_reg>       := continuous (min=0.1, max=10)
<DT>            := DT (criterion=<DT_criterion>)
<DT_criterion>  := categorical (options=['gini', 'entropy'])
Pipeline(classifier=LR(penalty='l1', reg=5.0100641442497995),
         decomposer=NoDec(), vectorizer=Count(ngram=1))
Pipeline(classifier=DT(criterion='entropy'), decomposer=SVD(n=132),
         vectorizer=TfIdf(ngram=1, use_idf=True))
Pipeline(classifier=SVM(kernel='poly', reg=4.920899781533629),
         decomposer=NoDec(), vectorizer=TfIdf(ngram=1, use_idf=False))
Pipeline(classifier=SVM(kernel='poly', reg=6.2324098495719165),
         decomposer=SVD(n=168), vectorizer=TfIdf(ngram=3, use_idf=False))
Pipeline(classifier=LR(penalty='l2', reg=1.1722788593996094),
         decomposer=NoDec(), vectorizer=TfIdf(ngram=3, use_idf=True))
Pipeline(classifier=LR(penalty='l1', reg=2.6947947887881387),
         decomposer=SVD(n=70), vectorizer=TfIdf(ngram=3, use_idf=True))
Pipeline(classifier=SVM(kernel='poly', reg=6.555178265496012),
         decomposer=SVD(n=161), vectorizer=TfIdf(ngram=3, use_idf=True))
Pipeline(classifier=SVM(kernel='poly', reg=0.11487924961813162),
         decomposer=NoDec(), vectorizer=Count(ngram=3))
Pipeline(classifier=SVM(kernel='poly', reg=3.3642041546657793),
         decomposer=SVD(n=69), vectorizer=TfIdf(ngram=3, use_idf=True))
Pipeline(classifier=DT(criterion='entropy'), decomposer=NoDec(),
         vectorizer=Count(ngram=1))
Restricting memory to 4294967296

Current Gen 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 41.58 evals/s]
Best: 0.000   0%|▍                                                                                                                                                                                   |    2/1000 [00:00<00:13, 78.01 evals/s]
Traceback (most recent call last):
  File "docs/examples/sklearn_simple_grammar.py", line 301, in <module>
    best_rand, fn_rand = random_search.run(1000, logger=logger)
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/search/_base.py", line 112, in run
    raise e from None
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/search/_base.py", line 105, in run
    fn = self._fitness_fn(solution)
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/utils/_process.py", line 75, in __call__
    return self.run_restricted(*args, **kwargs)
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/utils/_process.py", line 124, in run_restricted
    raise result
AttributeError: 'Pipeline' object has no attribute 'send'

Original Traceback (most recent call last):
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/utils/_process.py", line 40, in _restricted_function
    result = self.function(*args, **kwargs)
  File "/data/gblanco/virtualenvs/race-experiments/lib/python3.8/site-packages/autogoal/datasets/movie_reviews.py", line 37, in fitness_fn
    pipeline.send("train")
AttributeError: 'Pipeline' object has no attribute 'send'
```

Inspecting the code, I see that the [`fitness_fn`](https://github.com/autogoal/autogoal/blob/34d36ffa96c382d2da34202e3afaeb27c139e323/autogoal/datasets/movie_reviews.py#L37-L39) does a `send` call, isn't it a Sklearn Pipeline? In which case, there is no `send` nor `run` methods.

What is the purpose of those `send` calls? Maybe notify the worker process?

Best,

**Comment by apiad** [comment]
Thanks! I'm gonna have to run it. We have our own definition of `Pipeline` which does have a `send` method for internal purposes, but in this example, that should not be necessary. So maybe we have confused some imports here. This code hasn't been tried in a while.

Thanks for reporting!!!

**Comment by apiad** [comment]
This reminds me that we need to have some integration tests for running the experiments, at least one generation of each.

**Comment by geblanco** [comment]
Okay, so there is indeed a working Pipeline class, I'll have a look, thanks!
> Thanks! I'm gonna have to run it. We have our own definition of Pipeline which does have a send method for internal purposes, but in this example, that should not be necessary. So maybe we have confused some imports here. This code hasn't been tried in a while.

**Comment by apiad** [comment]
@all-contributors please add @geblanco for bugs
